export const MIN_DAYS_BETWEEN_SAME_OPPONENT = 2
export const SEASON_LENGTH_DAYS = 170
export const GAMES_PER_FRAME_INSTANT = 10
export const GAMES_PER_FRAME_NORMAL = 1
export const NORMAL_SIM_DELAY_MS = 150
