import { Info } from 'lucide-react'

export function AutoGeneratedBanner() {
  return (
    <div className="flex items-center gap-2 rounded-md border border-sky-500/30 bg-sky-500/10 px-3 py-2 text-sm text-sky-500">
      <Info className="size-4 shrink-0" />
      <span>
        Auto-generated rotation. Adjust freely — your changes are saved automatically.
      </span>
    </div>
  )
}
