import { useState, useMemo, useCallback, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { RotateCw, ArrowLeft } from 'lucide-react'
import { useGameStore } from '@/store/useGameStore'
import type { Player } from '@/game/models/player'
import { PageHeader } from '@/components/layout/PageHeader'
import { Button } from '@/components/ui/button'
import { rateLineup } from '@/game/ratings/lineupRatingEngine'
import type { RotationWarning } from '@/game/models/team'
import {
  computeRotationMinutesTotal,
  STARTER_SLOT_COUNT,
  uniquePlayerIds,
} from '@/game/management/rotationActions'
import { ValidationWarningsList, warningMessage } from '@/components/lineup/ValidationWarningsList'
import { AutoGeneratedBanner } from '@/components/lineup/AutoGeneratedBanner'
import { AutoRotateConfirmDialog } from '@/components/lineup/AutoRotateConfirmDialog'
import { PlayerPickerDialog } from '@/components/lineup/PlayerPickerDialog'
import { MinutesDistribution } from '@/components/charts/MinutesDistribution'
import { LineupRatingCard } from '@/components/lineup/LineupRatingCard'
import { MinutesTotalBar } from '@/components/lineup/MinutesTotalBar'
import { RotationBuilder } from '@/components/lineup/RotationBuilder'
import { ClosingLineupEditor } from '@/components/lineup/ClosingLineupEditor'
import { HelpButton } from '@/components/tutorial/HelpButton'

export function LineupPage() {
  const save = useGameStore((s) => s.save)
  const setStarters = useGameStore((s) => s.setStarters)
  const setBench = useGameStore((s) => s.setBench)
  const setClosingLineup = useGameStore((s) => s.setClosingLineup)
  const setTargetMinutes = useGameStore((s) => s.setTargetMinutes)
  const assignPlayerToRotation = useGameStore((s) => s.assignPlayerToRotation)
  const removePlayerFromRotation = useGameStore((s) => s.removePlayerFromRotation)
  const movePlayerInRotation = useGameStore((s) => s.movePlayerInRotation)
  const balanceRotationMinutes = useGameStore((s) => s.balanceRotationMinutes)
  const forceIncludePlayer = useGameStore((s) => s.forceIncludePlayer)
  const autoRotate = useGameStore((s) => s.autoRotate)
  const generateRotationIfMissing = useGameStore((s) => s.generateRotationIfMissing)

  const [autoRotateOpen, setAutoRotateOpen] = useState(false)
  const [pickerOpen, setPickerOpen] = useState(false)
  const [pickerTarget, setPickerTarget] = useState<{
    section: 'starters' | 'bench' | 'closing'
    index?: number
  } | null>(null)

  const teamId = save?.league.userTeamId
  const team = teamId ? save.league.teams[teamId] : null
  const lineup = team?.lineup

  useEffect(() => {
    if (team?.lineup && lineup?.starters.length === 0) {
      generateRotationIfMissing()
    }
  }, [team, lineup, generateRotationIfMissing])

  useEffect(() => {
    if (!lineup || !team) return
    const starters = uniquePlayerIds(lineup.starters)
    const bench = uniquePlayerIds(lineup.bench)
    const closing = uniquePlayerIds(lineup.closingLineup)
    if (
      starters.length !== lineup.starters.length ||
      bench.length !== lineup.bench.length ||
      closing.length !== lineup.closingLineup.length
    ) {
      setStarters(starters)
      setBench(bench)
      setClosingLineup(closing)
    }
  }, [lineup, team, setStarters, setBench, setClosingLineup])

  const players = useMemo(() => {
    if (!team || !save) return new Map<string, Player>()
    return new Map(
      Object.entries(save.league.players).filter(([id]) =>
        team.roster.includes(id),
      ),
    )
  }, [team, save])

  const allRotationIds = useMemo(() => {
    if (!lineup) return new Set<string>()
    return new Set([...lineup.starters, ...lineup.bench])
  }, [lineup])

  const minuteChartData = useMemo(() => {
    if (!lineup) return []
    const rotationIds = [...new Set([...lineup.starters, ...lineup.bench])]
    return rotationIds
      .map((id) => {
        const p = players.get(id)
        const target = lineup.targetMinutes[id] ?? 0
        if (target <= 0) return null
        const gp = Math.max(1, p?.seasonStats.gamesPlayed ?? 1)
        const mpg = p ? Math.round(p.seasonStats.minutes / gp) : 0
        return {
          name: p ? `${p.firstName.charAt(0)}. ${p.lastName}` : id.slice(0, 8),
          minutes: mpg,
          target,
        }
      })
      .filter((d): d is { name: string; minutes: number; target: number } => d !== null)
      .sort((a, b) => b.target - a.target)
  }, [lineup, players])

  const lineupRating = useMemo(() => {
    if (!lineup) return null
    const starterPlayers = lineup.starters
      .map((id) => players.get(id) ?? null)
      .filter((p): p is Player => p !== null)
    return rateLineup(starterPlayers, lineup.targetMinutes)
  }, [lineup, players])

  const totalMinutes = useMemo(
    () => (lineup ? computeRotationMinutesTotal(lineup) : 0),
    [lineup],
  )

  const handleAutoRotate = useCallback(() => {
    autoRotate()
  }, [autoRotate])

  const handleOpenPicker = useCallback(
    (section: 'starters' | 'bench' | 'closing', index?: number) => {
      setPickerTarget({ section, index })
      setPickerOpen(true)
    },
    [],
  )

  const handlePickerSelect = useCallback(
    (playerId: string) => {
      if (!pickerTarget || !lineup) return
      if (pickerTarget.section === 'starters') {
        assignPlayerToRotation(playerId, 'starter', pickerTarget.index)
      } else if (pickerTarget.section === 'bench') {
        if (lineup.bench.includes(playerId)) return
        assignPlayerToRotation(playerId, 'bench', pickerTarget.index)
      } else if (pickerTarget.section === 'closing') {
        const withoutPlayer = lineup.closingLineup.filter((id) => id !== playerId)
        const index = pickerTarget.index ?? withoutPlayer.length
        const next = [...withoutPlayer]
        if (index < STARTER_SLOT_COUNT) {
          if (index < next.length) {
            next[index] = playerId
          } else {
            next.push(playerId)
          }
          setClosingLineup(next)
        }
      }
      setPickerTarget(null)
    },
    [pickerTarget, lineup, assignPlayerToRotation, setClosingLineup],
  )

  const handleFixWarning = useCallback(
    (code: RotationWarning) => {
      if (
        code === 'no_ball_handler' ||
        code === 'no_center' ||
        code === 'not_five_starters'
      ) {
        setAutoRotateOpen(true)
      } else if (code === 'minutes_not_240') {
        balanceRotationMinutes()
      }
    },
    [balanceRotationMinutes],
  )

  if (!save || !team) {
    return (
      <div>
        <PageHeader
          eyebrow="Front Office"
          title="Lineup & Rotation"
          description="Set starters, bench order, target minutes, and closing lineup."
        />
        <div className="rounded-lg border border-[var(--color-line-soft)] bg-[var(--color-surface-1)] p-8 text-center">
          <p className="text-sm text-[var(--color-muted-foreground)] mb-4">
            Start a league to set a rotation.
          </p>
          <Button asChild>
            <Link to="/new-league">Start New League</Link>
          </Button>
        </div>
      </div>
    )
  }

  if (team.roster.length === 0) {
    return (
      <div>
        <PageHeader
          eyebrow="Front Office"
          title="Lineup & Rotation"
          description="Set starters, bench order, target minutes, and closing lineup."
        />
        <div className="rounded-lg border border-[var(--color-line-soft)] bg-[var(--color-surface-1)] p-8 text-center">
          <p className="text-sm text-[var(--color-muted-foreground)]">
            No players on this team.
          </p>
        </div>
      </div>
    )
  }

  if (!lineup) return null

  return (
    <div>
      <PageHeader
        eyebrow="Front Office"
        title="Lineup & Rotation"
        description={`${team.city} ${team.name} — ${team.roster.length} players`}
        actions={
          <div className="flex items-center gap-2">
            <HelpButton page="lineup" />
            <Button asChild variant="ghost" size="sm">
              <Link to="/roster">
                <ArrowLeft className="size-4" /> Roster
              </Link>
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setAutoRotateOpen(true)}
            >
              <RotateCw className="size-4" />
              Auto-rotate
            </Button>
          </div>
        }
      />

      <div className="space-y-6">
        {lineup.generatedByAutoRotate && <AutoGeneratedBanner />}

        <MinutesTotalBar
          totalMinutes={totalMinutes}
          onBalance={balanceRotationMinutes}
        />

        {lineup.lastValidationWarnings &&
          lineup.lastValidationWarnings.length > 0 && (
            <ValidationWarningsList
              warnings={lineup.lastValidationWarnings.map((code) => ({
                code,
                message: warningMessage(code),
              }))}
              onFix={handleFixWarning}
            />
          )}

        <RotationBuilder
          lineup={lineup}
          roster={team.roster}
          players={players}
          onMinutesChange={setTargetMinutes}
          onRemoveFromRotation={removePlayerFromRotation}
          onMovePlayer={movePlayerInRotation}
          onAssignPlayer={assignPlayerToRotation}
          onReorderBench={setBench}
          onForceIncludeChange={forceIncludePlayer}
          onOpenPicker={handleOpenPicker}
        />

        <ClosingLineupEditor
          closingIds={lineup.closingLineup}
          players={players}
          onReorder={setClosingLineup}
          onRemove={(id) =>
            setClosingLineup(lineup.closingLineup.filter((c) => c !== id))
          }
          onEmptySlotClick={(index) => handleOpenPicker('closing', index)}
          onPlayerClick={(index) => handleOpenPicker('closing', index)}
        />

        {lineupRating && <LineupRatingCard rating={lineupRating} />}

        {minuteChartData.length > 0 && (
          <MinutesDistribution players={minuteChartData} teamName={team.name} />
        )}
      </div>

      <AutoRotateConfirmDialog
        open={autoRotateOpen}
        onOpenChange={setAutoRotateOpen}
        onConfirm={handleAutoRotate}
      />

      <PlayerPickerDialog
        open={pickerOpen}
        onOpenChange={setPickerOpen}
        players={
          pickerTarget?.section === 'closing'
            ? Array.from(players.values()).filter((p) =>
                allRotationIds.has(p.id),
              )
            : Array.from(players.values())
        }
        disabledIds={
          pickerTarget?.section === 'closing'
            ? new Set(lineup.closingLineup)
            : allRotationIds
        }
        onSelect={handlePickerSelect}
      />
    </div>
  )
}
